sudo: required

language: java

services:
  - docker

before_install:
  - git clone https://github.com/PersonalHealthTrain/test.git
  - cd test/library
  - gradle publishToMavenLocal
  - cd ../..
  - gradle clean
