sudo: required

language: java

services:
  - docker

before_install:
  - gradle clean
  - export OLDPWD=$(pwd)
  - cd /tmp
  - git clone https://github.com/PersonalHealthTrain/test.git
  - cd test/library
  - gradle publishToMavenLocal
  - cd $OLDPWD
  - rm -rf /tmp/test

